spring:
  #Redis
  redis:
    host: localhost
    port: 6379
  #Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
